version: "3"

services:
  flutter:
    build: .
    image: "flutter-android-image" 
    container_name: "flutter-android" 
    tty: true
    environment:
      - no_proxy=127.0.0.1,localhost
      - DISPLAY=:1
    volumes:
      - "./app:/workdir/app" # あとでlongに修正する
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
      - /dev/kvm:/dev/kvm
    network_mode: "host"
